### ISSUE TITLE
Update interface on select change event

### ISSUE THREAD

**Issue by daltonjc** [masasron/Segment.js#1]
It would be great if this plugin would update the UI when the underlying select box value changes.

Right now if you've got some model-view binding going on and the select box is changed, the "active" class is not moved to the proper button to reflect the change.

I've got a fix coded up in a codepen which I could dump into a pull request later, if you're interested.

**Comment by masasron** [comment]
Hi @daltonjc 
Sorry about the delay, it will be much appreciated.
